language: node_js
node_js: stable
293889f6eda204c05ac957c4d3950a38b85cfdd2
install:
    - npm install

script:
    - gitbook build

after_script:
    - cd ./_book
    - git init
    - git config user.name "tonny travis"
    - git config user.email "wodexintiao@gmail.com"
    - git add .
    - git commit -m 'update docs'
    - git push -f -q "https://${GITHUB_TOKEN}@${GITHUB_REF}" master:gh-page

env:
    global:
        - GITHUB_REF: github.com/tonny-zhang/collection.git     
